import argparse
import json
import os
import re
import sys
import textwrap
import urllib.error
import urllib.request


DEFAULT_MODEL = "gpt-4o-mini"


def read_text(path):
    if path == "-":
        return sys.stdin.read()
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def write_text(path, text):
    if not path:
        print(text)
        return
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def bullet_lines(text):
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if re.match(r"^[-*]\s+", line):
            lines.append(re.sub(r"^[-*]\s+", "", line))
        elif re.match(r"^\d+[.)]\s+", line):
            lines.append(re.sub(r"^\d+[.)]\s+", "", line))
    return lines


def find_section(text, names):
    pattern = r"(?ims)^#+\s*(" + "|".join(re.escape(name) for name in names) + r").*?\n(.*?)(?=^#+\s|\Z)"
    match = re.search(pattern, text)
    return match.group(2).strip() if match else ""


def infer_owner(line):
    lowered = line.lower()
    if any(word in lowered for word in ["接口", "api", "server", "backend", "数据库"]):
        return "backend / service"
    if any(word in lowered for word in ["页面", "展示", "点击", "跳转", "按钮", "弹窗", "ui"]):
        return "frontend / app"
    if any(word in lowered for word in ["埋点", "统计", "track", "analytics"]):
        return "data / analytics"
    if any(word in lowered for word in ["测试", "验收", "case"]):
        return "qa"
    return "feature owner"


def risks_for(line):
    risks = []
    if any(word in line for word in ["登录", "权限", "未登录"]):
        risks.append("登录态和权限分支需要覆盖")
    if any(word in line for word in ["接口", "网络", "返回", "字段"]):
        risks.append("接口失败、字段缺失和兼容旧数据需要兜底")
    if any(word in line for word in ["跳转", "路由"]):
        risks.append("路由路径和参数需要联调确认")
    if any(word in line for word in ["时间", "过期", "倒计时", "expire"]):
        risks.append("时区、秒/毫秒单位和边界时间容易出错")
    return risks or ["需求边界不清时先补充验收样例"]


def heuristic_plan(text):
    title_match = re.search(r"(?m)^#\s+(.+)$", text)
    title = title_match.group(1).strip() if title_match else "Implementation Task Cards"
    requirement_text = find_section(text, ["需求", "功能", "Requirements", "Feature"]) or text
    acceptance_text = find_section(text, ["验收", "验收标准", "Acceptance", "AC"])
    requirements = bullet_lines(requirement_text) or [line.strip() for line in requirement_text.splitlines() if line.strip()][:6]
    acceptance = bullet_lines(acceptance_text)

    output = ["# Implementation Task Cards", "", "## Source", "", "- Title: %s" % title, "- Generated by: prd-tasksmith", ""]
    for index, item in enumerate(requirements, 1):
        output.extend([
            "## Task %d: %s" % (index, item[:46]),
            "",
            "- Goal: %s" % item,
            "- Owner hint: %s" % infer_owner(item),
            "- Inputs to confirm:",
            "  - 入口、接口字段、异常态和灰度范围",
            "- Acceptance:",
        ])
        if acceptance:
            for line in acceptance[:4]:
                output.append("  - %s" % line)
        else:
            output.append("  - 正常路径、边界路径、失败路径均可验证")
        output.append("- Risks:")
        for risk in risks_for(item):
            output.append("  - %s" % risk)
        output.append("")
    return "\n".join(output).rstrip() + "\n"


def call_ai(source, draft):
    api_key = os.getenv("AI_API_KEY")
    if not api_key:
        raise RuntimeError("AI_API_KEY is not set")
    base_url = os.getenv("AI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.getenv("AI_MODEL", DEFAULT_MODEL)
    prompt = """You are a senior product-engineering assistant.
Rewrite the draft into concise implementation task cards for developers.
Keep Markdown. Include goals, owners, risks, acceptance criteria, and questions.

PRD:
%s

Draft:
%s
""" % (source[:12000], draft[:12000])
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "Return only Markdown."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=data,
        headers={"Authorization": "Bearer " + api_key, "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError("AI request failed: %s" % exc)
    return body["choices"][0]["message"]["content"].strip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Turn a PRD into developer task cards.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
        Examples:
          python3 -m prd_tasksmith examples/sample_prd.md
          python3 -m prd_tasksmith PRD.md --ai --output TASKS.md
        """),
    )
    parser.add_argument("input", help="PRD file path, or '-' for stdin")
    parser.add_argument("--ai", action="store_true", help="Polish the local draft with an OpenAI-compatible model")
    parser.add_argument("--output", help="Write result to a file instead of stdout")
    args = parser.parse_args(argv)

    source = read_text(args.input)
    draft = heuristic_plan(source)
    result = call_ai(source, draft) if args.ai else draft
    write_text(args.output, result)


if __name__ == "__main__":
    main()
